### ISSUE TITLE
Installation errors Mac platform

### ISSUE THREAD

**Issue by GattiMh** [keiserlab/LUNA#42]
Hello,

I have followed the instructions in the document but when reaching the `python setup.py build` step, I get this error:

`ModuleNotFoundError:` No module named 'Bio._py3k'`

Which I think is related to biopython? I have it installed just in case but was wondering if anyone had the same error before.

Many thanks

**Comment by alexandrefassio** [comment]
Hi @GattiMh 

Thanks for your heads up and sorry for the error. This is, in fact, an error related to Biopython, but soon I'll fix it.

Meanwhile, I will update the installation instructions so that anyone got this error again. Also, it's in my plans to add full support to Conda.

While I don't make these changes, please, install LUNA as follows:

1) Download LUNA’s [environment.yml](https://github.com/keiserlab/LUNA/blob/master/luna-env.yml) file if you don't have it yet.
2) Create the Conda environment using the downloaded file:
`conda env create -f <LUNA-ENV-FILE>`
3) After creating the Conda environment, activate it:
`conda activate luna-env`
4) Finally, install LUNA from Pip:
`pip install luna`

It should work now, but if you have any new issues let me know. I'd be pleased to help you out.

bests

**Comment by alexandrefassio** [comment]
Hi @GattiMh,

It seems this error is related to Pymol license. To be honest, I have never found such an error. Could you please try to disable Pymol usage to test?

 To do so, use the following flag: `--no-pse`.

If it works, this is in fact something related to the Pymol license. I could then implement a way to set up licenses for Pymol.

bests

**Comment by GattiMh** [comment]
Thanks!

Unfortunately, that doesn't work. I think the reason is that my version of Pymol was not the open-source one.
I have installed the open source one but `run.py` still doesn't work. 

`python luna/run.py -p example/inputs/protein.pdb -l example/inputs/ligands.mol2 -e example/inputs/entries.txt -w dopamine_results
/Users/opt/miniconda3/lib/python3.8/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')

▨ Creating a new LUNA project: 'dopamine_results'...

/Users/opt/miniconda3/lib/python3.8/site-packages/luna/projects.py:317: LUNAWarning: Logging mode was set ON. Logging information will be saved from now on.
  self.logging_enabled = logging_enabled
[2023-02-15 10:41:31]    INFO            projects.py:557        LUNA version: 0.12.2.
[2023-02-15 10:41:31]    WARNING         projects.py:557        It was trying to create an invalid number of processes (-1). Therefore, the number of processes 'nproc' was set to its maximum accepted capacity (12 - 1 = 11).
[2023-02-15 10:41:31]    INFO            projects.py:557        Verbosity set to: 3 (INFO).
[2023-02-15 10:41:31]    INFO            projects.py:557        Preparing project directory 'dopamine_results'.
[2023-02-15 10:41:31]    WARNING         projects.py:557        The provided PDB path 'None' is not valid or does not exist. Therefore, PDBs will be saved at the working path: dopamine_results/pdbs/
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/chunks' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/configs' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/logs' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/pdbs' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/results/interactions' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/results/fingerprints' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/results/pse' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/results' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO                file.py:190        The directory 'dopamine_results/tmp' already exists, but it will not be cleared.
[2023-02-15 10:41:31]    INFO            projects.py:557        Project directory 'dopamine_results' created successfully.
[2023-02-15 10:41:31]    INFO            projects.py:557        Logging file 'dopamine_results/logs/project.log' initialized successfully.
[2023-02-15 10:41:31]    INFO            projects.py:557        The remotion of duplicate entries was finished. 0 entrie(s) were removed.
[2023-02-15 10:41:31]    INFO            projects.py:557        It will verify the existence of PDB files and download them as necessary.
[2023-02-15 10:41:31]    INFO            projects.py:669        0 PDB file(s) found at 'dopamine_results/pdbs/' from a total of 1 PDB(s). So, 1 PDB(s) need to be downloaded.
Traceback (most recent call last):
  File "luna/run.py", line 402, in <module>
    main()
  File "luna/run.py", line 324, in main
    pli_obj.run()
  File "/Users/opt/miniconda3/lib/python3.8/site-packages/luna/projects.py", line 902, in run
    self()
  File "/Users/opt/miniconda3/lib/python3.8/site-packages/luna/projects.py", line 1260, in __call__
    self.verify_pdb_files_existence()
  File "/Users/opt/miniconda3/lib/python3.8/site-packages/luna/projects.py", line 677, in verify_pdb_files_existence
    job_results = pj.run_jobs(args=args, consumer_func=download_pdb,
  File "/Users/opt/miniconda3/lib/python3.8/site-packages/luna/util/jobs.py", line 237, in run_jobs
    p.start()
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/opt/miniconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object`

**Comment by alexandrefassio** [comment]
Hi @GattiMh,

Really sorry for the very very long delay.

The last errors you sent me are not related to Pymol now. I searched for this error and found out it is related to multiprocessing, and mainly happens on Windows and Macs. Also, it seems this error is related to Pymol 3.8 because the default multiprocessing method changed in this version.

A user has suggested the following [code](https://github.com/Koed00/django-q/issues/389#issuecomment-687356587):
 
```
from multiprocessing import set_start_method
set_start_method("fork")
```
and some users confirmed this has helped. **Could you please help me test it on your machine?**
If it works, we'll be able to fix it once and for all.

To do so, open the file **luna/util/jobs.py** and add the above code at the top of the file.

Unfortunately, I don't have a Mac OS available for me to test it myself right now, but I'm installing a VM machine here on my laptop. I'll install Windows and Mac OS so that I can test this and other issues in the future. I'll also employ Travis CI in LUNA so that I can test LUNA on different platforms automatically,

bests

**Comment by GattiMh** [comment]
Many thanks for persisting in solving the problem.
The fix presented still doesn't work. I've changed machine and now I'm on an M1 Mac. Re-done all of the conda enviroment  and pip install, following the previous line to test the tool I get:

`python luna/run.py -p example/inputs/protein.pdb -l example/inputs/ligands.mol2 -e example/inputs/entries.txt -w dopamine_results
/Users/miniconda3/envs/luna-env/lib/python3.7/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
  warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')

▨ Creating a new LUNA project: 'dopamine_results'...

/Users/miniconda3/envs/luna-env/lib/python3.7/site-packages/luna/projects.py:317: LUNAWarning: Logging mode was set ON. Logging information will be saved from now on.
  self.logging_enabled = logging_enabled
[2023-04-05 10:25:40]    INFO            projects.py:557        LUNA version: 0.12.2.
[2023-04-05 10:25:40]    WARNING         projects.py:557        It was trying to create an invalid number of processes (-1). Therefore, the number of processes 'nproc' was set to its maximum accepted capacity (12 - 1 = 11).
[2023-04-05 10:25:40]    INFO            projects.py:557        Verbosity set to: 3 (INFO).
[2023-04-05 10:25:40]    INFO            projects.py:557        Preparing project directory 'dopamine_results'.
[2023-04-05 10:25:40]    WARNING         projects.py:557        The provided PDB path 'None' is not valid or does not exist. Therefore, PDBs will be saved at the working path: dopamine_results/pdbs/
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/chunks' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/configs' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/logs' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/pdbs' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/results/interactions' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/results/fingerprints' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/results/pse' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/results' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO                file.py:191        The directory 'dopamine_results/tmp' already exists, but it will not be cleared.
[2023-04-05 10:25:40]    INFO            projects.py:557        Project directory 'dopamine_results' created successfully.
[2023-04-05 10:25:40]    INFO            projects.py:557        Logging file 'dopamine_results/logs/project.log' initialized successfully.
[2023-04-05 10:25:40]    INFO            projects.py:557        The remotion of duplicate entries was finished. 0 entrie(s) were removed.
[2023-04-05 10:25:40]    INFO            projects.py:557        It will verify the existence of PDB files and download them as necessary.
[2023-04-05 10:25:40]    INFO            projects.py:672        0 PDB file(s) found at 'dopamine_results/pdbs/' from a total of 1 PDB(s). So, 1 PDB(s) need to be downloaded.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
[2023-04-05 10:25:40]    PROGRESS                               0% [                                                  ] 0/1 [Avg: 0.00s/task; Errors: 0] - Download PDBs.No such feature exists.
Feature:       PYMOL_MAIN
License path:  /Library/Application Support/Schrodinger/licenses/80_client_2023-03-28_maestro-license.lic:
FlexNet Licensing error:-5,147
`


I have re-installed Pymol in the new M1 machine using brew. You have to add `pip install PyQt5` and now I can open Pymol from the terminal within the environment.

**Comment by alexandrefassio** [comment]
Hi @GattiMh 

Installing a virtual machine MAC is still on my to-do list so that I can better debug issues related to this system.

But for now, were you able to fix your issue after installing PyQt5, or did I get it wrong?

bests

**Comment by alexandrefassio** [comment]
Feel free to reopen if you still need some help.
